package ui

const (
	symbolCopyright      = "©"
	symbolGitLab         = ""
	symbolGitHub         = ""
	symbolGit            = ""
	symbolLineBreak      = "\n"
	symbolNetworkPublic  = "󰞉"
	symbolNetworkPrivate = "󰕑"
	symbolUndefined      = ""
	symbolSite           = ""
	symbolAPI            = ""
	symbolDockerImage    = ""
	symbolNpmPackage     = ""
	symbolSEO            = "󰚩"
	symbolAuth           = ""
	symbolNotFound       = ""
	symbolError          = ""
	symbolDownload       = ""
	symbolSelectPrev     = ""
	symbolSelectNext     = ""
	symbolToggleHead     = "󰬌"
	symbolQuit           = "󰬘"
	symbolTooNew         = "󰎔"
	symbolSoGood         = ""
	symbolBeNice         = ""
	symbolTooOld         = "󰬟"
	symbolDashboard      = "󰡃"
)
