package uikit

const (
	SymbolCopyright      = "©"
	SymbolGitLab         = ""
	SymbolGitHub         = ""
	SymbolGit            = ""
	SymbolLineBreak      = "\n"
	SymbolNetworkPublic  = "󰞉"
	SymbolNetworkPrivate = "󰕑"
	SymbolUndefined      = ""
	SymbolSite           = ""
	SymbolAPI            = ""
	SymbolDockerImage    = ""
	SymbolNpmPackage     = ""
	SymbolSEO            = "󰚩"
	SymbolAuth           = ""
	SymbolNotFound       = ""
	SymbolError          = ""
	SymbolDownload       = ""
	SymbolAdd            = ""
	SymbolEdit           = ""
	SymbolDelete         = "󰧧"
	SymbolSelectPrev     = ""
	SymbolSelectNext     = ""
	SymbolToggleHead     = "󰬌"
	SymbolQuit           = "󰬘"
	SymbolTooNew         = "󰎔"
	SymbolSoGood         = ""
	SymbolBeNice         = ""
	SymbolTooOld         = "󰬟"
	SymbolDashboard      = "󰡃"
	SymbolStack          = ""
	SymbolNamespace      = ""
	SymbolDependency     = ""
	SymbolSource         = ""
	SymbolPolicy         = "󰯄"
)
